Django-1.10: Replace IPAddressField with GenericIPAddressField
$ esmond_manage migrate
cassandra_db [INFO] Checking/creating column families
cassandra_db [INFO] Schema check done
cassandra_db [DEBUG] Opening ConnectionPool
cassandra_db [INFO] Connected to ['localhost:9160']
SystemCheckError: System check identified some issues:

ERRORS:
api.IfRef.ipAddr: (fields.E900) IPAddressField has been removed except for support in historical migrations.
        HINT: Use GenericIPAddressField instead.
api.LSPOpStatus.dstAddr: (fields.E900) IPAddressField has been removed except for support in historical migrations.
        HINT: Use GenericIPAddressField instead.
api.LSPOpStatus.srcAddr: (fields.E900) IPAddressField has been removed except for support in historical migrations.
        HINT: Use GenericIPAddressField instead.